# Use official Python image as base
FROM python:3.11.7

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /microapp

# Install dependencies
COPY requirements.txt /microapp/requirements.txt
RUN pip install -r requirements.txt
RUN pip install pika
RUN python manage.py migrate
# Copy project files
COPY . /microapp/

# Expose port 8000 to access Django application
EXPOSE 8001

# Run Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
