version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - 8001:8001
    volumes:
      - .:/microapp

  queue:
    build: 
      context: .
      dockerfile: DockerFile
    command: 'python consumer.py'
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.9.8-management
    hostname: 'localhost'
    command: 'python '
    ports:
      - "5673:5672"  # RabbitMQ port
      - "15673:15672"  # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  db:
    image: postgres
    container_name: BookService-postgres
    restart: always
    environment:
      POSTGRES_DB: BookService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin!@7890
      
    ports:
      - "5433:5432"    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data