version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: ApiGateWay-postgres
    restart: always
    environment:
      POSTGRES_DB: GateWay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin!@7890
      
    ports:
      - "5434:5432"    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data