version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: DockerFile    
    ports:
      - 8000:8000
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3.9.8-management
    hostname: 'localhost'
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  

  db:
    image: postgres
    container_name: ApiGateWay-postgres
    restart: always
    environment:
      POSTGRES_DB: GateWay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin!@7890
      
    ports:
      - "5434:5432"    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data